apiVersion: flomesh.io/v1alpha1
kind: Proxy
metadata:
  name: pipy-standalone-009
spec:
  mode: Standalone
  replicas: 1
  image: flomesh/pipy-pjs:latest
  port: 6000
  config:
    config.js: |
      pipy()

      .listen(6000)
          .connect('127.0.0.1:6443', {
              tls: {},
          })

      .listen(6443, {
          tls: {
              cert: os.readFile('cert.pem').toString(),
              key: os.readFile('key.pem').toString(),
          },
      })
          .decodeHttpRequest()
          .replaceMessage(new Message('Hello!\n'))
          .encodeHttpResponse()
    key.pem: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAxd6VlapMf1eCY4gNCGKgjVnz6wqCB+y1tEbK80coEHSj78jy
      Au9og+T7ezxp03iN+h1pjbgzoHriA6TrQr2EU2JujwV31aG4q0r2qq6MuSG+afQn
      Rzn6NGjJNL+W7h7h7kmSSpT434NMchHM3z+9CxijSbEDBp/auiOzwDNpDs7Z3Wbj
      XheU7h7FCWDjJuNjauq+ue44LzLxkdm3xnXxYnHZSH6VMGBKY7NznaSuciM85zma
      uAVh+U/waFJEmyRgX1+9zlXLYFnpwNLf79VEW3gL6/yG7t0+CA7q3mq/aZzs872c
      MhNCcaOOcYgyyB+DQWT7vaiDCgqLbBCS5ief/wIDAQABAoIBAEUROO2REDqy9RSA
      /OucYaZ1a6rzdAgIHDTdMSJSCC4WSNL+NVvI7ZZ8azvNDrN+NTDE639IeNzfh9z1
      yBj3xiTFCwppQjcTyD4iYI+bdgt5N9oMG1nFZwy8Nt9usORVa0+d5q6Z6XU7g4ed
      pwGWYgppgzXJz+CUE+k9ZRUF3PoJpHq/LUoZoTUY1d7Ap8W7Z450x0Tb3j1OX/6R
      2aVVudMm82xjPYML3QVj8DpJ/rUXDvVqRumyv5l7UARw15+amqb7F8Lfu65A6x0m
      kf92kpGrrYZiejy9GVtArii/Zozc+CMlYXTOdJky+Ruoim1KIRWUbaOj9JhNv0nX
      wRjueaECgYEA8ohlLlFIYJmlpHeD/2/PamM+EWxxj8ZJOavd3vIsj03HEm+OV9Hw
      IOwOYfkBlMf8nQv1Uwk8/EIoHaJ/A8CR5dckR0YtmfxeU0O+JnZDPAEfUGJhasUP
      MyUuE2PhunINmvs5hFbvpwqXW1xOWS3noj4OMIRBHFtoivbJafzEJGsCgYEA0NtM
      us9oE/sDgF4LMOecQwwaMWFTnsXKGd/JLDtiDpZ4qHXv/qFX8cSgZTxQdNt1w9c5
      Zh81g+IYc+wtc0CEfMCosvCjwVOMSqMFbNFYLQ5QU3wtTJsQFuD5ttSUwVO7fXqr
      hdB8iRkqKjwyN4okYWWTuaGvG+FSux/s7egBd70CgYEAlRJU7qUzUXzfHToAvg6h
      dIjPa7I2EuMTuwjydMhxrxtlUuWSnlQBvpqZNIry99n8YSMqhQFWpM6dDaoFW+8P
      PjCAsfZmrRE7gP5QcB+cr9MYxjXSHuhEsXEW4wAvjIPx7OKhtcAhyZBu+86+sX3P
      tB9kZVnFE4LzvQZ3QlgEz0UCgYEAiBnQZ5AO365cesNOAaF8l8iELReiWT3E1JWb
      T+KmpKDzobuxGDplx9v9NdtXBr+Yf3V6Jw1BX17v1mLav1cUvwMBLBJac/oQ2vZe
      66mED2BbgfvSvS/zDSWwNK9U/KKm9D8DFSFmdiTa8Ejn5H91864w1PAC32U290/3
      opTkl/UCgYEAtc7Pv0scphXzp5qvreuVBmR8dI8yhzdUskueMbYeSB3MoHyo2gmx
      M+EWr1L05nJ48IVQ0sCnbFdUaYlW9o0JnE7cdYXpXW4EL9vP6dOM+Cn+cVJHOLPJ
      mjObgh5Fv3AF7ETP8A6ViMS5OYPhRnEIl+DUcP4Gv3H7nMudh56iXtE=
      -----END RSA PRIVATE KEY-----

    cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIICsjCCAZoCCQCjguRDfcUbtDANBgkqhkiG9w0BAQUFADAbMRkwFwYDVQQDDBBl
      eGFtcGxlLmNvbTo2NDQzMB4XDTIxMDMxNjEzMzQyNVoXDTIxMDQxNTEzMzQyNVow
      GzEZMBcGA1UEAwwQZXhhbXBsZS5jb206NjQ0MzCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBAMXelZWqTH9XgmOIDQhioI1Z8+sKggfstbRGyvNHKBB0o+/I
      8gLvaIPk+3s8adN4jfodaY24M6B64gOk60K9hFNibo8Fd9WhuKtK9qqujLkhvmn0
      J0c5+jRoyTS/lu4e4e5JkkqU+N+DTHIRzN8/vQsYo0mxAwaf2rojs8AzaQ7O2d1m
      414XlO4exQlg4ybjY2rqvrnuOC8y8ZHZt8Z18WJx2Uh+lTBgSmOzc52krnIjPOc5
      mrgFYflP8GhSRJskYF9fvc5Vy2BZ6cDS3+/VRFt4C+v8hu7dPggO6t5qv2mc7PO9
      nDITQnGjjnGIMsgfg0Fk+72ogwoKi2wQkuYnn/8CAwEAATANBgkqhkiG9w0BAQUF
      AAOCAQEAXVUkqxOy5IRPVGUkZvY8SrfjbklRNLpr9DBYOE/dxD+YoOsCI1irN4ds
      pR90D0yv8kn+OrxESfqKkbXW4DajxTgEbQg6lXxRnTT31IS52dn7h5b+rJ+KHuc0
      v5dc3soNiwRAyg2s62yxiGJ9gPeCSYC6dp29Ijyqwi9XUETQBCXnXAyB2gPh+SMv
      rSokxiz7hMRKvf8PHwARLQBHQqMJFRbefxImlFae60BOndcrZ6dAqZu+cqCiY+wl
      FL0g8XTU8la0q47kO09Ly/uEKq1XvUvr+KABSsolY/3CH8FNCT/Z8PE1LgvAgG3y
      ArfLXLuza7jAZYr/xqJJxDcdLSkC1g==
      -----END CERTIFICATE-----
