
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/control-plane: operator-manager
  name: operator-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      app.kubernetes.io/control-plane: operator-manager
      app.kubernetes.io/name: pipy-operator
      app.kubernetes.io/instance: operator-manager
