apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/control-plane: operator-manager
  name: operator-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/control-plane: operator-manager
    app.kubernetes.io/name: pipy-operator
    app.kubernetes.io/instance: operator-manager
