apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-injector
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: webhook
        args:
        - --enable-leader-election
        - --proxy-image=flomesh/pipy-pjs:latest
        - --proxy-init-image=flomesh/proxy-init:dev
        - --v=5