apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/control-plane: operator-manager
    flomesh.io/inject: "false"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-manager
  namespace: system
  labels:
    app.kubernetes.io/control-plane: operator-manager
    app.kubernetes.io/instance: operator-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/control-plane: operator-manager
      app.kubernetes.io/instance: operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/control-plane: operator-manager
        app.kubernetes.io/instance: operator-manager
    spec:
      containers:
      - command:
        - /operator-manager
        args:
        - --leader-elect
        - --v=2
        image: operator-manager:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: shared-mgr-res
          mountPath: /mgr
      volumes:
      - emptyDir: {}
        name: shared-mgr-res
      serviceAccountName: operator-manager
      terminationGracePeriodSeconds: 10
