
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: proxy-injector-webhook-cfg
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: proxy-injector-svc
      namespace: system
      path: /proxy-injector-flomesh-io-v1alpha1
  failurePolicy: Fail
  name: injector.flomesh.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
  namespaceSelector:
    matchLabels:
      flomesh.io/inject: "true"