apiVersion: v1
kind: Service
metadata:
  name: proxy-injector-svc
  namespace: system
spec:
  ports:
  - port: 443
    targetPort: 7443
    protocol: TCP
  selector:
    app.flomesh.io/name: pipy-operator
    app.flomesh.io/instance: proxy-injector